apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-agent
  labels:
    app: meta-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meta-agent
  template:
    metadata:
      labels:
        app: meta-agent
    spec:
      containers:
      - name: meta-agent
        image: devart/meta-agent:latest
        ports:
        - containerPort: 5000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: meta-agent-secrets
              key: openai-api-key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: meta-agent-secrets
              key: database-url
        - name: META_AGENT_API_KEY
          valueFrom:
            secretKeyRef:
              name: meta-agent-secrets
              key: meta-agent-api-key
        - name: API_BASE_URL
          value: "http://api-service:8787"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/meta-agent/status
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/meta-agent/status
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: meta-agent-service
spec:
  selector:
    app: meta-agent
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP